# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: 'Restore Nuget Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/TK.MongoDB.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'Build Project'

- task: file-creator@6
  inputs:
    filepath: 'TK.MongoDB.Repository.NetCore/TK.MongoDB.Tests/appsettings.json'
    filecontent: |
      {
        "ConnectionStrings": {
          "DefaultConnection": "mongodb://appuser:admin#123@95.138.142.17:5064/MongoDB_Repo_Test?authSource=admin&connect=direct"
        }
      }
  displayName: 'Add appsettings.json'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
  displayName: 'Pack Nuget Package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'